version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    target-branch: master
    labels:
      - "dependencies"
      - "skip-changelog"

  - package-ecosystem: "github-actions"
    target-branch: master
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "skip-changelog"
